%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Code to read binary data file generated by VU-Ams7fs device.
% Follow the mentioned steps to import AMS data:-

% 1)Open the data file(.7fs) using VU-DAMS software
% 2)Run this script post opening it in VU-DAMS software and follow tthe
% prompts
% 3)Don't close VU-DAMS before executing this script and finishing export
% 4)Exported data file is saved in the Documents folder as 'data.mat'

% @author: Aniket Mazumder
% @Organisation: Vrije Universiteit, Amsterdam
% @Copyright: Vrije Universiteit, Amsterdam
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clc
clear

file_names = [  "Z0.bin","DZ.bin","DZDT.bin","ECG.bin",...
                "MXR.bin","MYR.bin","MZR.bin",...
                "GyroX.bin","GyroY.bin","GyroZ.bin",...
                "magX.bin","magY.bin","magZ.bin",...
                "TicksA.bin","TicksB.bin","TicksD.bin","TicksG.bin","TicksM.bin",...
                "P_sc.bin","T_sc.bin","FILTDZ.bin","TicksARed.bin"];

%% TODO: Convert data to SI units
% scales for the data
scale_Z0=0.00047683721641078591;
scale_DZ=0.00047683721641078591;
scale_FILTDZ=0.00047683721641078591;
scale_DZDT=1;
scale_ECG=7.9472869401797652e-05;

scale_MXR=0.00048828125;
scale_MYR=scale_MXR;
scale_MZR=scale_MXR;

scale_GXR=0.06103515625;
scale_GYR=scale_GXR;
scale_GZR=scale_GXR;

scale_MagX=0.00014615608961321414;
scale_MagY=scale_MagX;
scale_MagZ=scale_MagX;

scale_Tick_A=1;%adc
scale_Tick_B=1;%battery
scale_Tick_D=1;%pressure
scale_Tick_G=1;%magneto
scale_Tick_M=1;%accel
scale_TickARed = 1;

scale_P_sc=1/253952;
scale_T_sc=1/524288;

c00=80715;
c10=-51786;
c20=-9062;
c30=-1195;
c01=-3956;
c11=1287;
c21=15;

scale_factor=[scale_Z0 scale_DZ scale_DZDT scale_ECG ...
             scale_MXR scale_MYR scale_MZR... 
             scale_GXR scale_GYR scale_GZR...
             scale_MagX scale_MagY scale_MagZ ...
             scale_Tick_A scale_Tick_B scale_Tick_D scale_Tick_G scale_Tick_M ...
             scale_P_sc scale_T_sc scale_FILTDZ scale_TickARed];

%% Construct the file path based on the operating system
if ispc  % Windows
    file_loc=input('Provide the location of participant data folder:','s');
    for i=1:length(file_names)
        file_path(i) = fullfile(file_loc, file_names(i));
    end
elseif ismac
    for i=1:length(file_names)
        file_path(i)=fullfile('/','var','folders','c6','6ps052qn5w79x5hrr4snxv2c0000gn','T','VU-DAMS','1711105604424','1711105618224',file_names(i));
    end
elseif isunix  % Unix/Linux
    for i=1:length(file_names)
        file_path(i) = fullfile('/','tmp','VU-DAMS','1724918174712','1724918181667', file_names(i));
    end
else
    error('Unsupported operating system.');
end

%Display message
disp('Converting ..., please wait');

file_ID=zeros(1,length(file_names));
disp('Done (1)')

%% Open the binary file for reading
for i=1:length(file_names)
    file_ID(i) = fopen(file_path(i), 'rb');
    if file_ID(i) == -1
        error('Unable to open the file.');
    end
end

% Read the binary data into a cell array
for i=1:length(file_names)
    data{:,i} = scale_factor(:,i)*fread(file_ID(i), Inf, 'int32','ieee-be');
end


%TODO: convert cell to double/number 
data=cell2table(data,"VariableNames", file_names);

tick_diff_filtDZ = diff(data.(22){1,1});

% check if any tick difference is greater than 150
if any(tick_diff_filtDZ > 150)
    % drop the sample
    data.(22){1,1}(tick_diff_filtDZ > 150) = [];
end

%% Repair file using ticks
% Z0=repair_holes(data.(14){1,1}',data.(1){1,1}');
% DZ=repair_holes(data.(14){1,1}',data.(2){1,1}');
% DZDT=repair_holes(data.(14){1,1}',data.(3){1,1}');
[ECG, time_ECG]=repair_holes(data.(14){1,1}',data.(4){1,1}');
MXR=repair_holes(data.(18){1,1}',data.(5){1,1}');
MYR=repair_holes(data.(18){1,1}',data.(6){1,1}');
MZR=repair_holes(data.(18){1,1}',data.(7){1,1}');
[GyroX, time_Gyro]=repair_holes(data.(18){1,1}',data.(8){1,1}');
GyroY=repair_holes(data.(18){1,1}',data.(9){1,1}');
GyroZ=repair_holes(data.(18){1,1}',data.(10){1,1}');
[magX, time_mag]=repair_holes(data.(17){1,1}',data.(11){1,1}');
% magY=repair_holes(data.(17){1,1}',data.(12){1,1}');
% magZ=repair_holes(data.(17){1,1}',data.(13){1,1}');
[Pressure, time_P]=repair_holes(data.(16){1,1}', data.(19){1,1}');
% Temp=repair_holes(data.(16){1,1}', data.(20){1,1}');
% FiltDZ= repair_holes(data.(22){1,1}',data.(21){1,1}');

% Find the max and mins of the ticks
%first_val=[data{1,14}{1,1}(1) data{1,15}{1,1}(1) data{1,16}{1,1}(1) data{1,17}{1,1}(1) data{1,18}{1,1}(1)];
%last_val= [data{1,14}{1,1}(end) data{1,15}{1,1}(end) data{1,16}{1,1}(end) data{1,17}{1,1}(end) data{1,18}{1,1}(end)];
max_first_val=max([time_ECG(1) time_mag(1) time_Gyro(1) time_P(1) ]);
min_last_val=min([time_ECG(end) time_mag(end) time_Gyro(end) time_P(end) ]);

%max_first_val=max(first_val);
%min_last_val=min(last_val);

%%
% time_array_ECG=(time_ECG>=max_first_val)&(time_ECG<=min_last_val);
time_array_P=(time_P>=max_first_val)&(time_P<=min_last_val);
time_array_Gyro=(time_Gyro>=max_first_val)&(time_Gyro<=min_last_val);
time_array_mag=(time_mag>=max_first_val)&(time_mag<=min_last_val);

% time_ECG_trim=time_ECG(time_array_ECG);
time_P_trim=time_P(time_array_P);
time_Gyro_trim=time_Gyro(time_array_Gyro);
% time_mag_trim=time_mag(time_array_mag);

% % ADC
% trimmed_ECG=ECG(time_array_ECG);
% trimmed_Z0=Z0(time_array_ECG);
% trimmed_DZDT=DZDT(time_array_ECG);
% trimmed_DZ=DZ(time_array_ECG);
% trimmed_Filt_DZ= FiltDZ(time_array_ECG); 
%Gyro
trimmed_GyroX=GyroX(time_array_Gyro);
trimmed_GyroY=GyroY(time_array_Gyro);
trimmed_GyroZ=GyroZ(time_array_Gyro);

%Acc
trimmed_MXR=MXR(time_array_Gyro);
trimmed_MYR=MYR(time_array_Gyro);
trimmed_MZR=MZR(time_array_Gyro);

% %Mag
% trimmed_magX=magX(time_array_mag);
% trimmed_magY=magY(time_array_mag);
% trimmed_magZ=magZ(time_array_mag);

% trimmed_Pressure=Pressure(time_array_P);
% trimmed_Temp=Temp(time_array_P);

% trimmed_Pressure=c00+trimmed_Pressure.*(c10+trimmed_Pressure.*(c20+trimmed_Pressure.*c30))+trimmed_Temp.*c01+trimmed_Temp.*trimmed_Pressure.*(c11+trimmed_Pressure.*c21);


% data=table(Z0,DZ,DZDT,ECG,MXR,MYR,MZR,GyroX,GyroY,GyroZ,magX,magY,magZ);
%data=table(Z0,DZ,DZDT,ECG,MXR,MYR,MZR,GyroX,GyroY,GyroZ,magX,magY,magZ,Pressure,Temp);
%  data=table(time_P_trim, trimmed_ECG , trimmed_Z0, trimmed_DZDT, trimmed_Filt_DZ, trimmed_DZ, ...
%      trimmed_GyroX, trimmed_GyroY, trimmed_GyroZ,...
%      trimmed_MXR, trimmed_MYR, trimmed_MZR,...
%      trimmed_magX, trimmed_magY, trimmed_magZ,...
%      trimmed_Pressure, trimmed_Temp);

data=table(time_P_trim, trimmed_GyroX, trimmed_GyroY, trimmed_GyroZ,...
     trimmed_MXR, trimmed_MYR, trimmed_MZR)

%Display message
disp('Done processing(2)')


%% Save the data to Documents directory and %delete temporary folder
% Extract individual arrays from the table
time=data.time_P_trim;
% ECG=data.trimmed_ECG;
% Z0 = data.trimmed_Z0;
% DZ = data.trimmed_DZ;
% DZDT = data.trimmed_DZDT;
% FILTDZ = data.trimmed_Filt_DZ;
MXR = data.trimmed_MXR;
MYR = data.trimmed_MYR;
MZR = data.trimmed_MZR;
GyroX = data.trimmed_GyroX;
GyroY = data.trimmed_GyroY;
GyroZ = data.trimmed_GyroZ;
% magX = data.trimmed_magX;
% magY = data.trimmed_magY;
% magZ = data.trimmed_magZ;
% Pressure = data.trimmed_Pressure;
% Temp = data.trimmed_Temp;

% Concatenate the arrays into a simpler array without column names
simpler_array = [time;MXR;MYR;MZR;GyroX;GyroY;GyroZ]';

% Save the simpler array
if(ispc)
    user = input('Enter the user name for the system:', 's');
    save_location = strcat('C:\Users\', user, '\Documents\data_91169.mat');
elseif(isunix || ismac)
    save_location = '~/Documents/data.mat';
else
    error('Unsupported operating system.');
end

% Save the simpler array
save(save_location, 'simpler_array', '-v7');
disp('Done saving simpler array.');

disp('Done (3)')


%% Close the files and exit
for i=1:length(file_names)
    if(fclose(file_ID(i))~=0)
        error('File close error')
    end
end

%Display message
disp('Done, final.')
%disp('For new file import -> close VUDAMS -> proceed with same steps');
% clear